sites:
  - id: uma_global
    source_site: uma_global
    base_url: "https://uma-global.pure-db.com/"
    searches:
      - name: example_search
        url: "https://uma-global.pure-db.com/?q=EXACT_QUERY"
