# .github/workflows/_cron_probe.yml
name: _cron_probe
on:
  schedule:
    - cron: "*/10 * * * *"
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - run: echo "event=${{ github.event_name }} utc=$(date -u +%FT%TZ)"
