name: UMA Monitor (reusable for external)

on:
  workflow_call:
    inputs:
      dry_run:        { type: boolean, default: false }
      sites_path:     { type: string,  required: true }   # path in caller repo
      tool_ref:       { type: string,  default: "main" }  # tag/branch of your repo to use
    secrets:
      CALLER_DISCORD_WEBHOOK:
        required: true

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout caller repo
        uses: actions/checkout@v4

      - name: Checkout tool (this repo)
        uses: actions/checkout@v4
        with:
          repository: haroldlkh/uma-db-alert
          ref: ${{ inputs.tool_ref }}
          path: tool

      - name: Install deps + browsers
        run: |
          python -m pip install -U pip
          pip install -r tool/requirements.txt
          python -m playwright install chromium

      - name: Cache Playwright
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-msplaywright-${{ hashFiles('tool/requirements.txt') }}
          restore-keys: ${{ runner.os }}-msplaywright-

      - name: Resolve sites config
        run: |
          test -f "${{ inputs.sites_path }}" || { echo "sites.yaml not found at ${{ inputs.sites_path }}"; exit 1; }
          cp "${{ inputs.sites_path }}" sites.effective.yaml

      - name: Restore state cache
        uses: actions/cache/restore@v4
        with:
          path: ~/.uma_monitor/${{ github.repository }}
          key: uma-state-v1-${{ github.repository }}
          restore-keys: |
            uma-state-v1-

      - name: Run orchestrator
        env:
          DISCORD_WEBHOOK_MAIN: ${{ secrets.CALLER_DISCORD_WEBHOOK }}
          # isolate cache per caller repo:
          UMA_STATE_DIR: ~/.uma_monitor/${{ github.repository }}
        run: |
          DRY=""
          if [ "${{ inputs.dry_run }}" = "true" ]; then DRY="--dry-run"; fi
          python tool/orchestrator.py \
            --sites sites.effective.yaml \
            --outputs tool/config/outputs.yaml \
            $DRY

      - name: Save state cache
        if: always()
        uses: actions/cache/save@v4
        with:
          path: ~/.uma_monitor/${{ github.repository }}
          key: uma-state-v1-${{ github.run_id }}
