# name: Example caller for other users

# permissions:
#   actions: write
#   contents: read

# on:
#   workflow_dispatch: # for manual runs
#     inputs:
#       dry_run:
#         description: "Check to run without posting"
#         type: boolean
#         default: false
#   schedule:
#     - cron: "0 * * * *"   # convert desired frequency to cron. Github max is every 5 minutes. At your own cost.

# jobs:
#   monitor:
#     uses: haroldlkh/uma-db-alert/.github/workflows/external-run-monitor.yaml@main
#     with:
#       dry_run: ${{ inputs.dry_run }}
#       sites_path: config/sites.yaml     # list of searches on uma-global-db
#       tool_ref: main
#       outputs_profiles: "discord_forum" # only option available right now
#     secrets:
#       CALLER_DISCORD_WEBHOOK_FORUM: ${{ secrets.MY_DISCORD_WEBHOOK }}