name: UMA Monitor (Staging)

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Check to run without sending alerts"
        type: boolean
        required: false
        default: "false"

jobs:
  staging:
    uses: ./.github/workflows/run-monitor.yaml
    with:
      dry_run: ${{ inputs.dry_run }}
      environment_name: "Staging"   # passes the env name to the called job
    # secrets:
    #   ENV_DISCORD_WEBHOOK: ${{ secrets.ENV_DISCORD_WEBHOOK }}
