name: UMA Monitor (Staging)

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Run without sending alerts (true/false)"
        required: false
        default: "true"

jobs:
  staging:
    uses: ./.github/workflows/run-monitor.yaml
    environment: Staging          # binds to your repo’s Staging env
    with:
      dry_run: ${{ inputs.dry_run == 'true' }}
    secrets: inherit               # forwards env secrets to the called workflow
