name: UMA Monitor (Staging)

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Run without sending alerts (true/false)"
        required: false
        default: "true"

jobs:
  staging:
    uses: ./.github/workflows/run-monitor.yaml
    with:
      dry_run: ${{ inputs.dry_run == 'false' }}
      environment_name: "Staging"   # passes the env name to the called job
    secrets:
      DISCORD_WEBHOOK_MAIN: ${{ secrets.DISCORD_WEBHOOK_MAIN }}
    # no `runs-on`, no `environment` here
    # no secrets mapping needed; the called job reads your env secret
