name: UMA Monitor (Staging)

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Check to run without sending alerts"
        type: boolean
        required: false
        default: "false"
      reset_state:
        type: boolean
        default: false

jobs:
  staging:
    uses: ./.github/workflows/run-monitor.yaml
    with:
      dry_run: ${{ inputs.dry_run }}
      environment_name: "Staging"
      outputs_profiles: "discord_forum"   # or "discord_forum,discord_text" later
    secrets:
      CALLER_DISCORD_WEBHOOK_FORUM: ${{ secrets.ENV_DISCORD_WEBHOOK }}
