name: UMA Monitor (Prod)

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Check to run without sending alerts"
        type: boolean
        required: false
        default: "false"

jobs:
  prod:
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'schedule' && vars.RUN_MONITOR == 'true') }}
    uses: ./.github/workflows/run-monitor.yaml
    with:
      dry_run: ${{ inputs.dry_run }}
      environment_name: "Prod"
    secrets:
      CALLER_DISCORD_WEBHOOK: ${{ secrets.PROD_DISCORD_WEBHOOK }}
